/*
 * generated by Xtext
 */
package org.codingvienna.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Dc6UiModule extends org.codingvienna.ui.AbstractDc6UiModule {
	public Dc6UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
