/*
* generated by Xtext
*/
package org.codingvienna.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class Dc6OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
