/*
* generated by Xtext
*/
package org.codingvienna.ui.contentassist;

import org.codingvienna.ui.contentassist.AbstractDc6ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Dc6ProposalProvider extends AbstractDc6ProposalProvider {

}
