/*
 * generated by Xtext
 */
package org.codingvienna.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess

class Dc6Generator implements IGenerator {
	
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		System::out.println("Test");
	}
}
