/*
* generated by Xtext
*/
package org.codingvienna;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Dc6UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.codingvienna.ui.internal.Dc6Activator.getInstance().getInjector("org.codingvienna.Dc6");
	}
	
}
