/*
 * generated by Xtext
 */
package org.codingvienna.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.codingvienna.ui.internal.Dc6Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Dc6ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Dc6Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Dc6Activator.getInstance().getInjector(Dc6Activator.ORG_CODINGVIENNA_DC6);
	}
	
}
