/*
 * generated by Xtext
 */
package org.codingvienna;


/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class Dc6RuntimeModule extends org.codingvienna.AbstractDc6RuntimeModule {

}
